version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
    ignore:
      - dependency-name: "@astrojs/cloudflare"
        update-types: ["version-update:semver-major"]
