nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  "astro@*":
    dependencies:
      typescript: "*"
  "@astrojs/language-server@*":
    dependencies:
      typescript: "*"