name: Pushover Notification
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - main
    - test
jobs:
  pushover-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          sound: 'pushover'
          title: 'New commit on GitHub'
